# .github/workflows/python-tests.yml

name: Python Tests # Workflow name, displayed in the GitHub Actions tab.

# Defines the triggers for this workflow.
on:
  push: # Triggers the workflow on push events.
    branches:
      - main # Specifically for pushes to the main branch.
      - develop # Also for pushes to the develop branch.
      # Additional branches or patterns can be specified here.
  pull_request: # Triggers the workflow on pull request events.
    branches:
      - main # Specifically for pull requests targeting the main branch.
      - develop # Also for pull requests targeting the develop branch.

jobs:
  test: # Defines a job named 'test'.
    runs-on: ubuntu-latest # Specifies the runner environment.
                           # Common choices: ubuntu-latest, windows-latest, macos-latest.

    strategy:
      matrix: # Defines a build matrix for running the job against multiple configurations.
        python-version: ["3.10", "3.11"] # List of Python versions to use.

    steps: # A sequence of tasks to be executed as part of the job.
    - name: Checkout code # Step 1: Checks out the repository's code.
      uses: actions/checkout@v4 # Uses the official GitHub action for checking out code.

    - name: Set up Python ${{ matrix.python-version }} # Step 2: Sets up the specified Python version from the matrix.
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch==2.2.1 torchvision==0.17.1 torchaudio==2.2.1 --index-url https://download.pytorch.org/whl/cu118
        pip install -r requirements.txt

    - name: Run tests with pytest # Step 4: Executes the test suite.
      run: |
        pytest # This command runs tests discovered by pytest.
        # To specify a particular test path:
        # pytest tests/